### ISSUE TITLE
Le facteur de couverture solaire peut être saisi

### ISSUE THREAD

**Issue by jgavignet** [jzck/Open3CL#176]
**Describe the bug**
Le facteur de couverture solaire peut être saisi

**To Reproduce**
DPE 2277E0998167B

**Expected behavior**
<fecs_saisi>0.26</fecs_saisi>

**Additional context**

- NodeJS version: [e.g. 18.16.0]

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify the tv_facteur_couverture_solaire function to allow for manual input of the solar coverage factor (fecs) when provided.

I also created pull request: https://github.com/jzck/Open3CL/pull/184


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
