### ISSUE TITLE
Le type d'adjacence pour les planchers hauts est souvent mal renseigné

### ISSUE THREAD

**Issue by jgavignet** [jzck/Open3CL#178]
**Describe the bug**
Le type d'adjacence pour les planchers hauts est souvent mal renseigné. Notamment pour les combles, la données peut être vérifiée depuis d'autres infos

**Additional context**

- NodeJS version: [e.g. 18.16.0]

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Added logic to verify and correct the adjacency type for upper floors, especially for attics, based on other available information. This addresses the issue of incorrectly specified adjacency types.

I also created pull request: https://github.com/jzck/Open3CL/pull/183


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
