### ISSUE TITLE
Facteur de couverture solaire pour le chauffage solaire en maison

### ISSUE THREAD

**Issue by jgavignet** [jzck/Open3CL#186]
**Describe the bug**
Le facteur de couverture solaire pour le chauffage solaire en maison n'est pas calculé

**To Reproduce**
2303E4293288R - Fch = 0.28

**Expected behavior**
![image](https://github.com/user-attachments/assets/180ad913-0eb8-4543-839c-60c45574e9e0)

**Additional context**

- NodeJS version: [e.g. 18.16.0]

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Add calculation of solar coverage factor (Fch) for solar heating in houses and use it in the heating consumption calculation.

I also created pull request: https://github.com/jzck/Open3CL/pull/187


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
