### ISSUE TITLE
Calcul des Umur pour 'isolation inconnue  (table forfaitaire)' - effet joule non pris en compte

### ISSUE THREAD

**Issue by jgavignet** [jzck/Open3CL#191]
**Describe the bug**
La variable pour effet joule n'est pas prise en compte pour le calcul des Umur pour le cas 'isolation inconnue  (table forfaitaire)' 

**To Reproduce**
2359E3937507Y

**Expected behavior**
Passer la variable effet joule dans le calcul

**Additional context**

- NodeJS version: [e.g. 18.16.0]

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the calc_mur function to include the 'ej' (effet joule) parameter when calling tv_umur for the 'isolation inconnue (table forfaitaire)' case. This ensures that the effet joule variable is considered in the Umur calculation for this specific scenario.

I also created pull request: https://github.com/jzck/Open3CL/pull/192


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
